---
- hosts: all
  connection: local
  name: Enable PXE on PCIe NIC
  gather_facts: False
  vars:
    pxe_devices:
      - NIC.Integrated.1-1-1
      - NIC.Integrated.1-3-1
      - NIC.Slot.5-1-1
      #- NIC.ChassisSlot.1-1-1 # FX2 PCIe NIC
      #- NIC.ChassisSlot.3-1-1 # FX2 PCIe NIC
      #- NIC.ChassisSlot.5-1-1 # FX2 PCIe NIC
      #- NIC.ChassisSlot.7-1-1 # FX2 PCIe NIC
  vars_files:
    - vault.yml
  tasks:
    - name: Get BIOS Attributes
      community.general.redfish_info: 
        baseuri: "{{ oob_host }}"
        username: "{{ vault_oob_username }}"
        password: "{{ vault_oob_password }}"
        category: Systems
        command: GetBiosAttributes
      register: result

    - name: Set BootMode
      set_fact:
        boot_mode: "{{ result.redfish_facts.bios_attribute.entries.0.1.BootMode }}"

    - name: Copy Template To File
      template:
        src: idrac-boot-pxe-enable.xml.j2
        dest: /tmp/idrac-boot-pxe-enable.xml

    - name: Import Server Configuration Profile
      dellemc.openmanage.idrac_server_config_profile:
        idrac_ip: "{{ oob_host }}"
        idrac_user: "{{ vault_oob_username }}"
        idrac_password: "{{ vault_oob_password }}"
        share_name: "/tmp"
        command: "import"
        scp_file: idrac-boot-pxe-enable.xml
        scp_components: "ALL"
        shutdown_type: "Graceful"
        job_wait: True
      register: result

    - name: UEFI
      block:

        - name: Set PxeDev1EnDis (UEFI)
          community.general.redfish_config:
            baseuri: "{{ oob_host }}"
            username: "{{ vault_oob_username }}"
            password: "{{ vault_oob_password }}"
            category: Systems
            command: SetBiosAttributes
            bios_attributes:
              PxeDev1EnDis: "Enabled"

        - name: Set PxeDev1Interface (LegacyBoot)
          community.general.redfish_config:
            baseuri: "{{ oob_host }}"
            username: "{{ vault_oob_username }}"
            password: "{{ vault_oob_password }}"
            category: Systems
            command: SetBiosAttributes
            bios_attributes:
              PxeDev1Interface: "{{ item }}"
          loop: "{{ pxe_devices }}" # FX2 Support. Sleds will have different PCIe NIC FQDD depending on the slot. 
          ignore_errors: True # FX2 Support. The PCIe NICs that aren't in a slot will fail. The one that is present will succeed. 
          register: result_uefi

      when: boot_mode == "Uefi" # Only run block when boot mode is Uefi

    - name: Create BIOS Config job
      community.general.idrac_redfish_command:
        category: Systems
        command: CreateBiosConfigJob
        baseuri: "{{ oob_host }}"
        username: "{{ vault_oob_username }}"
        password: "{{ vault_oob_password }}"
      when: result.changed or result_uefi.changed # Only run when things have changed

    - name: Restart sytem power gracefully
      community.general.redfish_command:
        category: Systems
        command: PowerGracefulRestart
        baseuri: "{{ oob_host }}"
        username: "{{ vault_oob_username }}"
        password: "{{ vault_oob_password }}"
      when: result.changed or result_uefi.changed # Only run when things have changed

    - name: Cleanup Files
      file:
        path: "/tmp/idrac-pxe-enable.xml"
        state: absent
