###
## Deploy OME Appliance 
###

- name: Deploy OME Appliance 
  hosts: all
  connection: local
  gather_facts: False
  vars:
    datacenter: "DC01"
    datastore: "Datastore01"
    resource_pool: "RP01"
    folder: "Folder01"
  vars_files:
    - vault.yml
  tasks:
  - community.vmware.vmware_deploy_ovf:
      hostname: "{{ vault_vcenter_host }}"
      username: "{{ vault_vcenter_username }}"
      password: "{{ vault_vcenter_password }}"
      validate_certs: no
      ovf: /mnt/iso/openmanage_enterprise_ovf_format_3.5/vmx/ovf/openmanage_enterprise.x86_64-0.0.1.ovf
      name: "OpenManage01"
      datacenter: "{{ datacenter }}"
      #cluster: "" # Comment this out if you want to use a Resource Pool
      resource_pool: "{{ resource_pool }}"
      networks: {"bridged": "VM Network"}  
      datastore: "{{ datastore }}"
      folder: "/{{ datacenter }}/vm/{{ folder }}"
    register: out1

  - debug: 
      var: out1