---
- hosts: localhost
  connection: local
  name: Groups
  gather_facts: False
  vars_files:
    - vault.yml
  tasks:
    - dellemc.openmanage.ome_groups:
        hostname: "{{ vault_ome_host }}"
        username: "{{ vault_ome_username }}"
        password: "{{ vault_ome_password }}"
        name: "Test1"
        description: "Test Group"
        parent: "Static Groups"
  
    - dellemc.openmanage.ome_device_group: 
        hostname: "{{ vault_ome_host }}"
        username: "{{ vault_ome_username }}"
        password: "{{ vault_ome_password }}"
        name: "Test"
        device_service_tags: 
          - "C39P9T2"
          - "C39N9T2"