###
## Deploy OME Appliance 
###

- name: Deploy OME Appliance 
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vault.yml
  tasks:
  - community.vmware.vmware_deploy_ovf:
      hostname: "{{ vault_vcenter_host }}"
      username: "{{ vault_vcenter_user }}"
      password: "{{ vault_vcenter_password }}"
      validate_certs: no
      ovf: /mnt/iso/openmanage_enterprise_ovf_format_3.5/vmx/ovf/openmanage_enterprise.x86_64-0.0.1.ovf
      name: "TS_OpenManage01"
      datacenter: "OSE Commercial DC"
      #cluster: "R730-RN-vSAN" # Leave this out if you want to use a Resource Pool
      resource_pool: "Trevor Squillario"
      networks: {"bridged": "vDs-Ent_Sandbox-1100"}  
      datastore: "CML2-VMwareProd-R730"
      folder: "/OSE Commercial DC/vm/Individual VMs/Trevor Squillario"
    register: out1

  - debug: 
      var: out1