---
- hosts: mx-chassis
  connection: local
  name: Provision Host
  gather_facts: False
  vars:
    baseline_name: "MX_IOM"
    catalog_name: "Dell.com"
    device_servicetags: ["F1SW673"] # Specify device service tag to limit by IOM. Leave array empty [] to query devices in chassis. Use with chassis_filter.
    dup_file_path: "/path/Network_Firmware_NTRW0_WN64_14.07.07_A00-00_01.EXE"
  vars_files:
    - vault.yml
  tasks:
    - block:
        - name: Get compute devices
          dellemc.openmanage.ome_device_info:
            hostname: "{{ vault_ome_host }}"
            username: "{{ vault_ome_username }}"
            password: "{{ vault_ome_password }}"
            fact_subset: "basic_inventory"
            system_query_options:
              filter: "Type eq 4000" # 4000 = Network IOM Device Type
          register: output_device_info

          - name: Build a list of device service tags 
            set_fact:
              device_servicetags: "{{ device_servicetags }} + [ '{{ item.DeviceServiceTag }}' ]"
            loop: "{{ output_device_info.device_info.value }}"
      when: device_servicetags | length == 0 # Don't run when specifing device_servicetags manually

    - debug:
        var: device_servicetags

    - name: Create baseline for devices
      dellemc.openmanage.ome_firmware_baseline:
        hostname:  "{{ hostname }}"
        username: "{{ vault_ome_username }}"
        password: "{{ vault_ome_password }}"
        baseline_name: "{{ baseline_name }}"
        catalog_name: "{{ catalog_name }}"
        device_service_tags: "{{ device_servicetags }}"
      #ignore_errors: true # Fails if object exists https://github.com/dell/dellemc-openmanage-ansible-modules/issues/146

    - name: Wait for baseline creation
      pause:
        seconds: 10

    - name: Update firmware for all sleds using baseline
      dellemc.openmanage.ome_firmware:
        hostname:  "{{ vault_ome_host }}"
        username: "{{ vault_ome_username }}"
        password: "{{ vault_ome_password }}"
        baseline_name: "{{ baseline_name }}"
      notify: WaitForJob
      register: output
      #ignore_errors: true # Fails if no updates required https://github.com/dell/dellemc-openmanage-ansible-modules/issues/252

#    - name: Update IOM Firmware # Legacy DUP update method
#      dellemc.openmanage.ome_firmware:
#        hostname: "{{ vault_ome_host }}"
#        username: "{{ vault_ome_username }}"
#        password: "{{ vault_ome_password }}"
#        device_service_tag: "{{ service_tag }}"
#        dup_file: "{{ dup_file_path }}"
#      notify: WaitForJob
#      register: output

  handlers:
    - name: WaitForJob
      dellemc.openmanage.ome_job_info:
        hostname:  "{{ hostname }}"
        username: "{{ vault_ome_username }}"
        password: "{{ vault_ome_password }}"
        job_id: "{{ output.update_status.Id }}"
      register: output_job
      failed_when: output_job.job_info.LastRunStatus.Name == 'Failed'
      changed_when: output_job.job_info.LastRunStatus.Name == 'Completed'
      until: output_job.job_info.LastRunStatus.Name in ['Completed', 'Failed', 'Warning', 'Aborted', 'Paused', 'Stopped', 'Cancelled']
      retries: 90 
      delay: 10 # 15 Minutes