---
- hosts: mx
  connection: local
  name: Get Device Inventory by Service Tag
  gather_facts: False
  vars_files:
    - vault.yml
  tasks:
    - name: Get device id by service tag
      dellemc.openmanage.ome_device_info:
        hostname:  "{{ default_ome_host }}"
        username: "{{ vault_ome_username }}"
        password: "{{ vault_ome_password }}"
        fact_subset: "basic_inventory"
        system_query_options:
          filter: "DeviceServiceTag eq '{{ service_tag }}'"
      register: output

    - copy:
        content: "{{ output }}"
        dest: "/tmp/dellemc.openmanage.ome_device_info_basic_{{inventory_hostname}}.txt"

    - set_fact:
        device_id: "{{ output.device_info.value[0].Id }}"
        cacheable: yes

    - set_fact:
        device_model: "{{ output.device_info.value[0].Model }}"
        cacheable: yes

    - set_fact:
        device_idrac_ip: "{{ output.device_info.value[0].DeviceManagement[0].NetworkAddress }}"
        cacheable: yes
    
    - set_fact:
        device_idrac_mac: "{{ output.device_info.value[0].DeviceManagement[0].MacAddress }}"
        cacheable: yes

    - debug:
        var: "{{ item }}"
      loop:
        - device_id
        - device_model
        - device_idrac_ip
        - device_idrac_mac

    - name:
      debug:
        msg: "Rackmount"
      when: device_model is match("PowerEdge R.*")

    - name:
      debug:
        msg: "FX2"
      when: device_model is match("PowerEdge FC.*")

    - name:
      debug:
        msg: "MX7000"
      when: device_model is match("PowerEdge MX.*")

    - name: Get detailed hardware inventory 
      dellemc.openmanage.ome_device_info:
        hostname: "{{ default_ome_host }}"
        username: "{{ vault_ome_username }}"
        password: "{{ vault_ome_password }}"
        fact_subset: "detailed_inventory"
        system_query_options:
          device_service_tag:
            - "{{ service_tag }}"
      register: deviceinfo

    - copy:
        content: "{{ deviceinfo }}"
        dest: "/tmp/dellemc.openmanage.ome_device_info_{{inventory_hostname}}.txt"