---
- hosts: MX740c-C39P9T2
  connection: local
  name: Discover
  gather_facts: False
  vars:
    retries_count: 100
    polling_interval: 10
    domain: "gcnose.adc.delllabs.net"
  vars_files:
    - vault.yml
  tasks:
    - ome_discovery:
        hostname: "{{ default_ome_host }}"
        username: "{{ vault_ome_username }}"
        password: "{{ vault_ome_password }}"
        #schedule: "run_later"
        #schedule_cron: "0 0 0 * * ? *" # Daily
        #schedule_cron: "0 19 19 16 5 ? 2019" # Later at Date
        name: "AnsibleTestNew3"
        discover_range: 
        #  - "{{ oob_host }}"
        #  - "192.168.2.100/26"
          - "MX740c-C39P9T2"
          - "MX840c-C39N9T2"
        discover_username: "root"
        discover_password: "{{ vault_ome_password }}"
        trap_destination: False
        device_type: "server"
        state: absent
      register: output

#    - debug:
#        var: output

#    - name: "Track job details for the discovery using a job id."
#      dellemc.openmanage.ome_job_info:
#        hostname: "{{ default_ome_host }}"
#        username: "{{ vault_ome_username }}"
#        password: "{{ vault_ome_password }}"
#        job_id: "{{ output.discover_status.DiscoveryConfigTaskParam[0].TaskId }}"
#      register: job_result
#      until: job_result.job_info.LastRunStatus.Name == 'Completed' or job_result.job_info.LastRunStatus.Name == 'Failed' or job_result.job_info.LastRunStatus.Name == 'Warning'
#      failed_when: job_result.job_info.LastRunStatus.Name == 'Failed'
#      changed_when: job_result.job_info.LastRunStatus.Name == 'Completed'
#      retries: "{{ retries_count }}"
#      delay: "{{ polling_interval }}"