---
- hosts: localhost
  connection: local
  name: Discover
  gather_facts: False
  vars:
    retries_count: 100
    polling_interval: 10
  vars_files:
    - vault.yml
  tasks:
    - name: Discover servers in a range
      dellemc.openmanage.ome_discovery:
        hostname: "{{ vault_ome_host }}"
        username: "{{ vault_ome_username }}"
        password: "{{ vault_ome_password }}"
        discovery_job_name: "Discovery Server 01"
        discovery_config_targets:
          - network_address_detail:
              - "192.35.0.0"
            #  - "192.36.0.0-10.36.0.255"
            #  - "192.37.0.0/24"
            #  - "2345:f2b1:f083:135::5500/118"
            #  - "2345:f2b1:f083:135::a500-2607:f2b1:f083:135::a600"
            #  - "hostname.domain.tld"
            #  - "hostname"
            #  - "2345:f2b1:f083:139::22a"
            device_types:
              - SERVER
            wsman:
              username: "root"
              password: "{{ vault_ome_password }}"
        job_wait: False
      register: output

    - debug:
        var: output

#    - name: "Track job details for the discovery using a job id."
#      dellemc.openmanage.ome_job_info:
#        hostname: "{{ vault_ome_host }}"
#        username: "{{ vault_ome_username }}"
#        password: "{{ vault_ome_password }}"
#        job_id: "{{ output.discover_status.JobId }}"
#      register: job_result
#      until: job_result.job_info.LastRunStatus.Name == 'Completed' or job_result.job_info.LastRunStatus.Name == 'Failed' or job_result.job_info.LastRunStatus.Name == 'Warning'
#      failed_when: job_result.job_info.LastRunStatus.Name == 'Failed'
#      changed_when: job_result.job_info.LastRunStatus.Name == 'Completed'
#      retries: "{{ retries_count }}"
#      delay: "{{ polling_interval }}"