- hosts: switches
  connection: network_cli
  gather_facts: no
  vars:
    backup: true
  vars_files:
    - vault.yml
  tasks:
    - name: "Get Dell EMC Show version"
      dellemc.os10.os10_command:
        commands: ['show version']
      register: show_ver

    - debug:
        var: show_ver

    - name: "Backup Running Config"
      dellemc.os10.os10_command:
        commands: ['copy running-configuration scp://root:calvin@192.168.1.102/mnt/data/mx9116_backup.txt']
      when: backup
