# Based on https://www.dell.com/support/kbdoc/en-us/000132936/how-to-generate-and-collect-support-bundle-in-dell-emc-networking-os10-switches
- hosts: switches
  connection: network_cli
  gather_facts: no
  vars:
    cleanup: true
    generate: false
    download: false
    supportbundles: []
  vars_files:
    - vault.yml
  tasks:
    - name: "Generate Support Bundle"
      dellemc.os10.os10_command:
        commands: ['generate support-bundle enable-all-plugin-options']
      when: generate

    - name: "Waiting for 20 Minutes Support Bundle to Finish."
      pause:
        minutes: 20
      when: generate

# ***This doesn't work when multiple bundles are generated. It will match on a previous BUNDLE_COMPLETED message in the log.
#    - name: "Waiting for Support Bundle to Finish. *This can take up to 15 minutes"
#      dellemc.os10.os10_command:
#        commands:
#          - show logging log-file
#        interval: 15
#        retries: 120 # 30 Minutes
#        wait_for:
#        - result[0] contains BUNDLE_COMPLETED
#      when: generate

    - name: "Get Support Bundles"
      dellemc.os10.os10_command:
        commands:
          - dir supportbundle
      register: out_supportbundle

    - debug:
        var: out_supportbundle

    - name: "Create List of Bundle Names to Download"
      set_fact:
        supportbundles: "{{ supportbundles }} + [ '{{ item | trim | regex_search(regexp_extract) }}' ]"
      vars:
        regexp_extract: 'sosreport-(.+)'
        regexp_match: 'sosreport-.*.tar.xz$'
      loop: "{{ out_supportbundle.stdout_lines[0] }}"
      when: item | trim | regex_search(regexp_match)

    - debug:
        var: supportbundles

    - name: "Download Support Bundles"
      dellemc.os10.os10_command:
        commands:
          - "copy supportbundle://{{ item }} scp://backup:password@192.168.1.100/mnt/data/backup/{{ item }}"
      loop: "{{ supportbundles }}"
      when: download

    - name: "Remove Support Bundles"
      dellemc.os10.os10_command:
        commands:
          - command: "delete supportbundle://{{ item }}*"
            prompt: "Proceed to delete"
            answer: "Yes"
      loop: "{{ supportbundles }}"
      when: cleanup